---
name: run ci on pull_request_target

on:
  pull_request_target:

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 
      - run: echo test
